version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql:/var/lib/mysql
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD= 1
      - MYSQL_DATABASE= db
    ports: 
      - 3306:3306
      - 33060:33060
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    depends_on: 
      - mysql
  app:
    image: golang:1.15.12
volumes:
  mysql:
  